language: node_js

node_js:
  - '0.10'
  - '4'
  - '5'
  - '6'

script:
  - npm run jscpd
  - npm run lint
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
